# Generated by Django 3.2.5 on 2021-07-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0002_alter_firma_cnpj'),
        ('agiota', '0002_agiota_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agiota',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firma.firma'),
        ),
    ]
