# Generated by Django 3.2.5 on 2021-08-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agiota', '0003_alter_agiota_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='agiota',
            name='pagou',
            field=models.BooleanField(default=True),
        ),
    ]
