# Generated by Django 3.2.5 on 2021-07-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='juros',
            field=models.CharField(choices=[('0', '---selecione---'), ('1', '5'), ('2', '10'), ('3', '15'), ('4', '20'), ('5', '25'), ('6', '30')], default='0', max_length=3),
        ),
    ]
