# Generated by Django 3.2.5 on 2021-07-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_alter_emprestimo_juros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='juros',
            field=models.CharField(choices=[('0', '---selecione---'), ('1', '5'), ('2', '10'), ('3', '15'), ('4', '20'), ('5', '25'), ('6', '30')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='parcela',
            field=models.CharField(choices=[('0', '---selecione---'), ('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05'), ('6', '06'), ('7', '07'), ('8', '08'), ('9', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=3),
        ),
    ]
