# Generated by Django 3.2.5 on 2021-07-29 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0002_alter_firma_cnpj'),
        ('emprestimo', '0004_emprestimo_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firma.firma'),
        ),
    ]
