# Generated by Django 3.2.5 on 2021-07-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_agiota'),
        ('emprestimo', '0005_emprestimo_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='juros',
            field=models.CharField(choices=[('0', '---selecione---'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30')], default='1', max_length=3),
        ),
    ]
