# Generated by Django 3.2.5 on 2021-08-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0009_auto_20210802_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='num_parcela',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
