# Generated by Django 3.2.5 on 2021-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0011_emprestimo_data_quitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='val_parcel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
