# Generated by Django 3.2.5 on 2021-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0012_emprestimo_val_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='em_aberto',
            field=models.BooleanField(default=False),
        ),
    ]
