# Generated by Django 3.2.5 on 2021-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0013_emprestimo_em_aberto'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_em_aberto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
