# Generated by Django 3.2.5 on 2021-07-27 01:56

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agiota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('agiota_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agiota.agiota')),
                ('status', models.BooleanField(default=False)),
                ('rg', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=15)),
                ('celular_cliente', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=200)),
                ('nome_ref', models.CharField(max_length=50)),
                ('rua_ref', models.CharField(max_length=50)),
                ('num_ref', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('agiota.agiota',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
